# Generated by Django 2.2.3 on 2019-08-20 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediaportal_app', '0005_auto_20190728_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
